package main.gui;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;

import javax.swing.JOptionPane;

import manager.Manager;
import player.Profile;
import util.FrolfUtil;
import discs.Disc;
import frolf.Course;
import frolf.Hole;
import frolf.Scorecard;
import frolf.Scorecard.ScorecardSummary;

/**
 *
 * @author Aaron
 */
public class App extends javax.swing.JFrame {
    private Manager manager;
    private Profile currentProfile;
    private Course currentCourse;
    
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        initializeApp();
    }
    
    public void updateDiscDisplay(Disc disc) {
        tDiscName.setText(disc.getName());

        switch(disc.getManufacturer()) {
            case INNOVA:
                tManufacturer.setText("Innova");
                break;
            default:
                tManufacturer.setText("?");
                break;
        }
        tManufacturer.setText(disc.getManufacturer().toString());
        tDiscType.setText(disc.getDiscType().toString());
        tSpeed.setText("" + disc.getSpeed());
        tGlide.setText("" + disc.getGlide());
        tTurn.setText("" + disc.getTurn());
        tFade.setText("" + disc.getFade());
    }
	
    public void updateProfile() {
        tUsername.setText(currentProfile.getUsername());
        tDisplayName.setText(currentProfile.getDisplayName());
        tStartDate.setText(currentProfile.getStartDate().toString());
        if (currentProfile.isRightHanded()) tHanded.setText("Right");
        else tHanded.setText("Left");
        tFavoriteDisc.setText(currentProfile.getFavoriteDiscName());
        tFavoriteCourse.setText(currentProfile.getFavoriteCourseName());
        tGamesPlayed.setText("" + currentProfile.getGamesPlayed());
        tHolesinone.setText("" + currentProfile.getHolesInOne());
        tEagles.setText("" + currentProfile.getEagles());
        tBirdies.setText("" + currentProfile.getBirdies());
        
        tProfileSummary.setText(currentProfile.getProfileSummary());
        System.out.println(currentProfile.getProfileSummary());
    }
    
    private void loadCourse(Course course) {
        // Clear scorecard
        clearScorecard();
        // Add par values to scorecard
        for (int holeNumber = 0; holeNumber < course.getNumberOfHoles(); holeNumber++) {
            Hole hole = course.getHole(holeNumber + 1); // +1 to match human #
            tblScorecard.setValueAt(hole.getPar(), holeNumber, 1);
        }
    }
    
    public void clearScorecard() {
        for (int column = 1; column < 4; column++){
            for (int row = 0; row < 18; row++)
            tblScorecard.setValueAt("", row, column);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pAppTabs = new javax.swing.JTabbedPane();
        pPlayerHome = new javax.swing.JPanel();
        pProfile = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        tUsername = new javax.swing.JLabel();
        lblDisplayName = new javax.swing.JLabel();
        tDisplayName = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        tStartDate = new javax.swing.JLabel();
        btnChangePicture = new javax.swing.JButton();
        btnEditProfile = new javax.swing.JButton();
        lblHanded = new javax.swing.JLabel();
        btnSwitchProfile = new javax.swing.JButton();
        tHanded = new javax.swing.JLabel();
        lblFavoriteDisc = new javax.swing.JLabel();
        tFavoriteDisc = new javax.swing.JLabel();
        lblFavoriteCourse = new javax.swing.JLabel();
        tFavoriteCourse = new javax.swing.JLabel();
        lblHolesinone = new javax.swing.JLabel();
        tHolesinone = new javax.swing.JLabel();
        lblEagles = new javax.swing.JLabel();
        tEagles = new javax.swing.JLabel();
        lblBirdies = new javax.swing.JLabel();
        tBirdies = new javax.swing.JLabel();
        lblBirdies1 = new javax.swing.JLabel();
        tGamesPlayed = new javax.swing.JLabel();
        pBag = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tProfileSummary = new javax.swing.JTextArea();
        btnAddDisc = new javax.swing.JButton();
        btnRemoveDisc = new javax.swing.JButton();
        btnRemoveDisc1 = new javax.swing.JButton();
        pDiscsHome = new javax.swing.JPanel();
        discSelector = new javax.swing.JComboBox();
        lblDiscName = new javax.swing.JLabel();
        tDiscName = new javax.swing.JLabel();
        tManufacturer = new javax.swing.JLabel();
        lblManufacturer = new javax.swing.JLabel();
        lblDiscType = new javax.swing.JLabel();
        tDiscType = new javax.swing.JLabel();
        tSpeed = new javax.swing.JLabel();
        lblSpeed = new javax.swing.JLabel();
        lblGlide = new javax.swing.JLabel();
        tGlide = new javax.swing.JLabel();
        tTurn = new javax.swing.JLabel();
        lblTurn = new javax.swing.JLabel();
        tFade = new javax.swing.JLabel();
        lblFade = new javax.swing.JLabel();
        pScorecard = new javax.swing.JPanel();
        tScoreScroll = new javax.swing.JScrollPane();
        tblScorecard = new javax.swing.JTable();
        btnLoadGriggs = new javax.swing.JButton();
        btnLoadBalgriffen = new javax.swing.JButton();
        btnFinishRound = new javax.swing.JButton();
        btnSaveProfiles = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pAppTabs.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        pProfile.setBackground(new java.awt.Color(0, 153, 255));
        pProfile.setPreferredSize(new java.awt.Dimension(300, 400));

        javax.swing.GroupLayout pProfileLayout = new javax.swing.GroupLayout(pProfile);
        pProfile.setLayout(pProfileLayout);
        pProfileLayout.setHorizontalGroup(
            pProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        pProfileLayout.setVerticalGroup(
            pProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        lblUsername.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblUsername.setText("Username:");

        tUsername.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tUsername.setText("<!>");

        lblDisplayName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblDisplayName.setText("Display Name:");

        tDisplayName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tDisplayName.setText("<!>");

        lblStartDate.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblStartDate.setText("Start Date:");

        tStartDate.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tStartDate.setText("<!>");

        btnChangePicture.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnChangePicture.setText("Change Picture");

        btnEditProfile.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditProfile.setText("Edit Profile");

        lblHanded.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblHanded.setText("L/R Handed:");

        btnSwitchProfile.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSwitchProfile.setText("Switch Profile");
        btnSwitchProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSwitchProfileMousePressed(evt);
            }
        });

        tHanded.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tHanded.setText("<!>");

        lblFavoriteDisc.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblFavoriteDisc.setText("Favorite Disc:");

        tFavoriteDisc.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tFavoriteDisc.setText("<!>");

        lblFavoriteCourse.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblFavoriteCourse.setText("Favorite Course:");

        tFavoriteCourse.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tFavoriteCourse.setText("<!>");

        lblHolesinone.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblHolesinone.setText("Holes in 1:");

        tHolesinone.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tHolesinone.setText("<!>");

        lblEagles.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblEagles.setText("Eagles:");

        tEagles.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tEagles.setText("<!>");

        lblBirdies.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblBirdies.setText("Birdies:");

        tBirdies.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tBirdies.setText("<!>");

        lblBirdies1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblBirdies1.setText("Games Played:");

        tGamesPlayed.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tGamesPlayed.setText("<!>");

        pBag.setBackground(new java.awt.Color(255, 0, 0));

        tProfileSummary.setColumns(20);
        tProfileSummary.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        tProfileSummary.setRows(5);
        jScrollPane1.setViewportView(tProfileSummary);

        javax.swing.GroupLayout pBagLayout = new javax.swing.GroupLayout(pBag);
        pBag.setLayout(pBagLayout);
        pBagLayout.setHorizontalGroup(
            pBagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBagLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pBagLayout.setVerticalGroup(
            pBagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBagLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        btnAddDisc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddDisc.setText("Add Disc to Bag");

        btnRemoveDisc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRemoveDisc.setText("Lost a Disc :[ (or sold it)");

        btnRemoveDisc1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRemoveDisc1.setText("Recommend a Disc for Me!");
        btnRemoveDisc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRemoveDisc1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout pPlayerHomeLayout = new javax.swing.GroupLayout(pPlayerHome);
        pPlayerHome.setLayout(pPlayerHomeLayout);
        pPlayerHomeLayout.setHorizontalGroup(
            pPlayerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPlayerHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPlayerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPlayerHomeLayout.createSequentialGroup()
                        .addComponent(pBag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(pPlayerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSwitchProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChangePicture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddDisc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRemoveDisc, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(btnRemoveDisc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pPlayerHomeLayout.createSequentialGroup()
                        .addGroup(pPlayerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pPlayerHomeLayout.createSequentialGroup()
                                .addComponent(lblUsername)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tUsername))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pPlayerHomeLayout.createSequentialGroup()
                                .addComponent(lblDisplayName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tDisplayName))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pPlayerHomeLayout.createSequentialGroup()
                                .addComponent(lblStartDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tStartDate))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pPlayerHomeLayout.createSequentialGroup()
                                .addComponent(lblHanded)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tHanded))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pPlayerHomeLayout.createSequentialGroup()
                                .addComponent(lblFavoriteDisc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tFavoriteDisc))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pPlayerHomeLayout.createSequentialGroup()
                                .addComponent(lblFavoriteCourse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                                .addComponent(tFavoriteCourse))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pPlayerHomeLayout.createSequentialGroup()
                                .addComponent(lblHolesinone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tHolesinone))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pPlayerHomeLayout.createSequentialGroup()
                                .addComponent(lblEagles)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tEagles))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pPlayerHomeLayout.createSequentialGroup()
                                .addComponent(lblBirdies)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tBirdies))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pPlayerHomeLayout.createSequentialGroup()
                                .addComponent(lblBirdies1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tGamesPlayed)))
                        .addGap(18, 18, 18)
                        .addComponent(pProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pPlayerHomeLayout.setVerticalGroup(
            pPlayerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPlayerHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPlayerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPlayerHomeLayout.createSequentialGroup()
                        .addGroup(pPlayerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsername)
                            .addComponent(tUsername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pPlayerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDisplayName)
                            .addComponent(tDisplayName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pPlayerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStartDate)
                            .addComponent(tStartDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pPlayerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHanded)
                            .addComponent(tHanded))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pPlayerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFavoriteDisc)
                            .addComponent(tFavoriteDisc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pPlayerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFavoriteCourse)
                            .addComponent(tFavoriteCourse))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pPlayerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHolesinone)
                            .addComponent(tHolesinone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pPlayerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEagles)
                            .addComponent(tEagles))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pPlayerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBirdies)
                            .addComponent(tBirdies))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pPlayerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBirdies1)
                            .addComponent(tGamesPlayed)))
                    .addComponent(pProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pPlayerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPlayerHomeLayout.createSequentialGroup()
                        .addComponent(btnChangePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSwitchProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveDisc1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                    .addComponent(pBag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pAppTabs.addTab("Player Home", pPlayerHome);

        discSelector.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        discSelector.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                discSelectorItemStateChanged(evt);
            }
        });

        lblDiscName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblDiscName.setText("Name:");

        tDiscName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tDiscName.setText("<!>");

        tManufacturer.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tManufacturer.setText("<!>");

        lblManufacturer.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblManufacturer.setText("Manufacturer:");

        lblDiscType.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblDiscType.setText("Type:");

        tDiscType.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tDiscType.setText("<!>");

        tSpeed.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tSpeed.setText("<!>");

        lblSpeed.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblSpeed.setText("Speed:");

        lblGlide.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblGlide.setText("Glide:");

        tGlide.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tGlide.setText("<!>");

        tTurn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tTurn.setText("<!>");

        lblTurn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblTurn.setText("Turn:");

        tFade.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tFade.setText("<!>");

        lblFade.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblFade.setText("Fade:");

        javax.swing.GroupLayout pDiscsHomeLayout = new javax.swing.GroupLayout(pDiscsHome);
        pDiscsHome.setLayout(pDiscsHomeLayout);
        pDiscsHomeLayout.setHorizontalGroup(
            pDiscsHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDiscsHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDiscsHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(discSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pDiscsHomeLayout.createSequentialGroup()
                        .addGroup(pDiscsHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTurn)
                            .addComponent(lblGlide)
                            .addComponent(lblSpeed)
                            .addComponent(lblDiscType)
                            .addComponent(lblManufacturer)
                            .addComponent(lblDiscName)
                            .addComponent(lblFade))
                        .addGap(18, 18, 18)
                        .addGroup(pDiscsHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tFade)
                            .addComponent(tDiscName)
                            .addComponent(tManufacturer)
                            .addComponent(tDiscType)
                            .addComponent(tSpeed)
                            .addComponent(tGlide)
                            .addComponent(tTurn))))
                .addContainerGap(383, Short.MAX_VALUE))
        );
        pDiscsHomeLayout.setVerticalGroup(
            pDiscsHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDiscsHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(discSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pDiscsHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiscName)
                    .addComponent(tDiscName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDiscsHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacturer)
                    .addComponent(tManufacturer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDiscsHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiscType)
                    .addComponent(tDiscType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDiscsHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpeed)
                    .addComponent(tSpeed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDiscsHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGlide)
                    .addComponent(tGlide))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDiscsHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTurn)
                    .addComponent(tTurn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDiscsHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFade)
                    .addComponent(tFade))
                .addContainerGap(373, Short.MAX_VALUE))
        );

        pAppTabs.addTab("Discs Home", pDiscsHome);

        tblScorecard.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tblScorecard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, "", ""},
                {"2", null, "", ""},
                {"3", null, "", ""},
                {"4", null, "", ""},
                {"5", null, "", ""},
                {"6", null, "", ""},
                {"7", null, "", ""},
                {"8", null, "", ""},
                {"9", null, "", ""},
                {"10", null, "", ""},
                {"11", null, "", ""},
                {"12", null, "", ""},
                {"13", null, "", ""},
                {"14", null, "", ""},
                {"15", null, "", ""},
                {"16", null, "", ""},
                {"17", null, "", null},
                {"18", null, "", null}
            },
            new String [] {
                "Hole", "Par", "Aaron", "Anthony"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblScorecard.setRowHeight(24);
        tScoreScroll.setViewportView(tblScorecard);

        btnLoadGriggs.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnLoadGriggs.setText("Load Griggs");
        btnLoadGriggs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLoadGriggsMousePressed(evt);
            }
        });

        btnLoadBalgriffen.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnLoadBalgriffen.setText("Load Balgriffen");
        btnLoadBalgriffen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLoadBalgriffenMousePressed(evt);
            }
        });

        btnFinishRound.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnFinishRound.setText("Finish Round");
        btnFinishRound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinishRoundMouseClicked(evt);
            }
        });

        btnSaveProfiles.setText("Save Profiles");
        btnSaveProfiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSaveProfilesMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pScorecardLayout = new javax.swing.GroupLayout(pScorecard);
        pScorecard.setLayout(pScorecardLayout);
        pScorecardLayout.setHorizontalGroup(
            pScorecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pScorecardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pScorecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnFinishRound, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                    .addComponent(tScoreScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pScorecardLayout.createSequentialGroup()
                        .addComponent(btnLoadGriggs, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLoadBalgriffen, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSaveProfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        pScorecardLayout.setVerticalGroup(
            pScorecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pScorecardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tScoreScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pScorecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoadGriggs)
                    .addComponent(btnLoadBalgriffen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(pScorecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSaveProfiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFinishRound, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addContainerGap())
        );

        pAppTabs.addTab("Scorecard", pScorecard);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pAppTabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pAppTabs)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void discSelectorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_discSelectorItemStateChanged
        String discName = (String)discSelector.getSelectedItem();
        updateDiscDisplay(manager.getDiscs().getDisc(discName));
    }//GEN-LAST:event_discSelectorItemStateChanged

    private void btnSwitchProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSwitchProfileMousePressed
        if (currentProfile.getUsername().compareTo("andersonmaaron") == 0) {
            currentProfile = manager.getProfiles().get("orsobianco");
        } else {
            currentProfile = manager.getProfiles().get("andersonmaaron");
        }
        
        updateProfile();
    }//GEN-LAST:event_btnSwitchProfileMousePressed

    private void btnLoadGriggsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadGriggsMousePressed
        loadCourse(manager.getCourses().get("Griggs Reservoir Park"));
        currentCourse = manager.getCourses().get("Griggs Reservoir Park");
    }//GEN-LAST:event_btnLoadGriggsMousePressed

    private void btnLoadBalgriffenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadBalgriffenMousePressed
        loadCourse(manager.getCourses().get("Balgriffen Park"));
        currentCourse = manager.getCourses().get("Balgriffen Park");
    }//GEN-LAST:event_btnLoadBalgriffenMousePressed

    private void btnFinishRoundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinishRoundMouseClicked
        String courseName = currentCourse.getName();
        
        HashMap<String, ArrayList<Integer>> theScores
                = new HashMap<String, ArrayList<Integer>>();
        ArrayList<Integer> theirScore = new ArrayList<Integer>();
        ArrayList<Integer> thePars = new ArrayList<Integer>();

        for (int column = 1; column < tblScorecard.getColumnCount(); column++) {

            theirScore = new ArrayList<Integer>();

            for (int row = 0; row < currentCourse.getNumberOfHoles(); row++) {

                Object obj = tblScorecard.getModel().getValueAt(row, column);
                int cell = 0;
                if (obj instanceof Integer)
                    cell = (int) obj;
                else
                    cell = Integer.parseInt((String) obj);

                if (column == 1) { // Par 
                    thePars.add(cell);
                } else { // Player score 
                    theirScore.add(cell);
                }
            }

            String username = tblScorecard.getColumnName(column);

            if (column != 1) {
                theScores.put(username, theirScore);
            }
        }

        Scorecard scorecard = new Scorecard(
                courseName,
                theScores,
                thePars
        );
        
        HashMap<String, ScorecardSummary> summaries = scorecard.getSummaries();
        for (String profileName : summaries.keySet()) {
            if (profileName.compareTo("Aaron") == 0) {
                manager.getProfiles().get("andersonmaaron").updateFromScorecard(summaries.get("Aaron"));
            } else if (profileName.compareTo("Anthony") == 0) {
                manager.getProfiles().get("orsobianco").updateFromScorecard(summaries.get("Anthony"));
            } else {
                System.out.println("Dunno...");
            }
        }
        clearScorecard();
    }//GEN-LAST:event_btnFinishRoundMouseClicked

    private void btnRemoveDisc1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveDisc1MousePressed
        Disc recommendedDisc = null;
        recommendedDisc = FrolfUtil.recommendDiscForBag(currentProfile.getDiscs());
        JOptionPane.showMessageDialog(this, recommendedDisc.getName());
    }//GEN-LAST:event_btnRemoveDisc1MousePressed

    private void btnSaveProfilesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveProfilesMousePressed
        HashMap<String, Profile> profiles = manager.getProfiles();
        for (String username : profiles.keySet()) {
            try {
				profiles.get(username).save();
			} catch (IOException e) {
				e.printStackTrace();
			}
        }
    }//GEN-LAST:event_btnSaveProfilesMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }
    
    private void initializeApp() {
        manager = Manager.getInstance();
        for (Disc disc : manager.getDiscs().getDiscs()) {
            discSelector.addItem(disc.getName());
        }
        
        currentProfile = manager.getProfiles().get("andersonmaaron");
        currentCourse = manager.getCourses().get("Griggs Reservoir Park");
        updateProfile();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDisc;
    private javax.swing.JButton btnChangePicture;
    private javax.swing.JButton btnEditProfile;
    private javax.swing.JButton btnFinishRound;
    private javax.swing.JButton btnLoadBalgriffen;
    private javax.swing.JButton btnLoadGriggs;
    private javax.swing.JButton btnRemoveDisc;
    private javax.swing.JButton btnRemoveDisc1;
    private javax.swing.JButton btnSaveProfiles;
    private javax.swing.JButton btnSwitchProfile;
    private javax.swing.JComboBox discSelector;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBirdies;
    private javax.swing.JLabel lblBirdies1;
    private javax.swing.JLabel lblDiscName;
    private javax.swing.JLabel lblDiscType;
    private javax.swing.JLabel lblDisplayName;
    private javax.swing.JLabel lblEagles;
    private javax.swing.JLabel lblFade;
    private javax.swing.JLabel lblFavoriteCourse;
    private javax.swing.JLabel lblFavoriteDisc;
    private javax.swing.JLabel lblGlide;
    private javax.swing.JLabel lblHanded;
    private javax.swing.JLabel lblHolesinone;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblSpeed;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblTurn;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTabbedPane pAppTabs;
    private javax.swing.JPanel pBag;
    private javax.swing.JPanel pDiscsHome;
    private javax.swing.JPanel pPlayerHome;
    private javax.swing.JPanel pProfile;
    private javax.swing.JPanel pScorecard;
    private javax.swing.JLabel tBirdies;
    private javax.swing.JLabel tDiscName;
    private javax.swing.JLabel tDiscType;
    private javax.swing.JLabel tDisplayName;
    private javax.swing.JLabel tEagles;
    private javax.swing.JLabel tFade;
    private javax.swing.JLabel tFavoriteCourse;
    private javax.swing.JLabel tFavoriteDisc;
    private javax.swing.JLabel tGamesPlayed;
    private javax.swing.JLabel tGlide;
    private javax.swing.JLabel tHanded;
    private javax.swing.JLabel tHolesinone;
    private javax.swing.JLabel tManufacturer;
    private javax.swing.JTextArea tProfileSummary;
    private javax.swing.JScrollPane tScoreScroll;
    private javax.swing.JLabel tSpeed;
    private javax.swing.JLabel tStartDate;
    private javax.swing.JLabel tTurn;
    private javax.swing.JLabel tUsername;
    private javax.swing.JTable tblScorecard;
    // End of variables declaration//GEN-END:variables

}
