package main.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import manager.Manager;
import util.FrolfUtil;
import discs.Disc;
import frolf.Scorecard;

/**
 *
 * @author Aaron Anderson
 */
public class Home extends javax.swing.JFrame {
	
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }
    
    public void updateProfile() {
    	tProfileSummary.setText(Manager.getInstance().getCurrentProfile().getProfileSummary());
    	DefaultListModel<String> dlm = new DefaultListModel<String>();
    	for (Disc disc : Manager.getInstance().getCurrentProfile().getDiscs().getDiscs()){
    		dlm.addElement(disc.getName());
    	}
    	lDiscs.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pEncloser = new javax.swing.JPanel();
        pProfilePic = new javax.swing.JPanel();
        pDiscDisplay = new javax.swing.JPanel();
        sDiscs = new javax.swing.JScrollPane();
        lDiscs = new javax.swing.JList();
        pProfileSummary = new javax.swing.JPanel();
        sProfileSummary = new javax.swing.JScrollPane();
        tProfileSummary = new javax.swing.JTextArea();
        pToolbar = new javax.swing.JPanel();
        tlToolBar = new javax.swing.JToolBar();
        btnViewDiscs = new javax.swing.JButton();
        btnRecommend = new javax.swing.JButton();
        btnPlayRound = new javax.swing.JButton();
        btnViewGames = new javax.swing.JButton();
        mMenuBar = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        miChangeProfile = new javax.swing.JMenuItem();
        miCreateProfile = new javax.swing.JMenuItem();
        miAddDisc = new javax.swing.JMenuItem();
        mEdit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pProfilePic.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout pProfilePicLayout = new javax.swing.GroupLayout(pProfilePic);
        pProfilePic.setLayout(pProfilePicLayout);
        pProfilePicLayout.setHorizontalGroup(
            pProfilePicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );
        pProfilePicLayout.setVerticalGroup(
            pProfilePicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pDiscDisplay.setBackground(new java.awt.Color(153, 255, 255));
        pDiscDisplay.setBorder(javax.swing.BorderFactory.createTitledBorder("Discs"));

        sDiscs.setViewportView(lDiscs);

        javax.swing.GroupLayout pDiscDisplayLayout = new javax.swing.GroupLayout(pDiscDisplay);
        pDiscDisplay.setLayout(pDiscDisplayLayout);
        pDiscDisplayLayout.setHorizontalGroup(
            pDiscDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDiscDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sDiscs, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );
        pDiscDisplayLayout.setVerticalGroup(
            pDiscDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDiscDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sDiscs, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );

        pProfileSummary.setBackground(new java.awt.Color(102, 204, 0));

        tProfileSummary.setColumns(20);
        tProfileSummary.setRows(5);
        sProfileSummary.setViewportView(tProfileSummary);

        javax.swing.GroupLayout pProfileSummaryLayout = new javax.swing.GroupLayout(pProfileSummary);
        pProfileSummary.setLayout(pProfileSummaryLayout);
        pProfileSummaryLayout.setHorizontalGroup(
            pProfileSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProfileSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sProfileSummary)
                .addContainerGap())
        );
        pProfileSummaryLayout.setVerticalGroup(
            pProfileSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProfileSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sProfileSummary)
                .addContainerGap())
        );

        pToolbar.setBackground(new java.awt.Color(204, 255, 255));

        tlToolBar.setBackground(new java.awt.Color(0, 153, 153));
        tlToolBar.setRollover(true);

        btnViewDiscs.setText("View Disc Catalogue");
        btnViewDiscs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnViewDiscsMousePressed(evt);
            }
        });
        tlToolBar.add(btnViewDiscs);

        btnRecommend.setText("Recommend a Disc!");
        btnRecommend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRecommendMousePressed(evt);
            }
        });
        tlToolBar.add(btnRecommend);

        btnPlayRound.setText("Play a Round!");
        btnPlayRound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPlayRoundMousePressed(evt);
            }
        });
        tlToolBar.add(btnPlayRound);

        btnViewGames.setText("View Past Games");
        btnViewGames.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnViewGamesMousePressed(evt);
            }
        });
        tlToolBar.add(btnViewGames);

        javax.swing.GroupLayout pToolbarLayout = new javax.swing.GroupLayout(pToolbar);
        pToolbar.setLayout(pToolbarLayout);
        pToolbarLayout.setHorizontalGroup(
            pToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tlToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pToolbarLayout.setVerticalGroup(
            pToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tlToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pEncloserLayout = new javax.swing.GroupLayout(pEncloser);
        pEncloser.setLayout(pEncloserLayout);
        pEncloserLayout.setHorizontalGroup(
            pEncloserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEncloserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEncloserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pEncloserLayout.createSequentialGroup()
                        .addComponent(pProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pDiscDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pProfileSummary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pEncloserLayout.setVerticalGroup(
            pEncloserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEncloserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEncloserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pProfilePic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pDiscDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pProfileSummary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mFile.setText("File");

        miChangeProfile.setText("Change Profile");
        miChangeProfile.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		miChangeProfileActionPerformed(e);
        	}
        });
        mFile.add(miChangeProfile);
        
        miCreateProfile.setText("Create Profile");
        miCreateProfile.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		miCreateProfileActionPerformed(e);
        	}
        });
        mFile.add(miCreateProfile);
        
        mMenuBar.add(mFile);

        mEdit.setText("Edit");
        miAddDisc.setText("Add disc to profile");
        miAddDisc.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		miAddDiscActionPerformed(e);
        	}
        });
        
        mEdit.add(miAddDisc);
        mMenuBar.add(mEdit);
        setJMenuBar(mMenuBar);
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pEncloser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pEncloser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }

    private void btnViewDiscsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewDiscsMousePressed
    	java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiscViewer().setVisible(true);
            }
        });
    }

    private void btnRecommendMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecommendMousePressed
    	if (Manager.getInstance().getCurrentProfile() == null) {
    		JOptionPane.showMessageDialog(null, "Please load a profile first.");
    		return;
    	}
        Disc recommendedDisc = FrolfUtil.recommendDiscForBag(Manager.getInstance().getCurrentProfile().getDiscs());
        JOptionPane.showMessageDialog(null, "" + recommendedDisc.getName());
    }

    private void btnPlayRoundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayRoundMousePressed
    	java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayRound().setVisible(true);
            }
        });
    }

    private void btnViewGamesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewGamesMousePressed
    	File[] gameFiles = new File("rounds").listFiles();
    	File selectedGame = (File) JOptionPane.showInputDialog(this, 
    	        "Select a game.",
    	        "Game View Select",
    	        JOptionPane.QUESTION_MESSAGE, 
    	        null, 
    	        gameFiles, 
    	        gameFiles[0]);
    	
    	Scorecard round = FrolfUtil.readRoundFromFile(selectedGame);
    	System.out.println("");
    }

    private void miChangeProfileActionPerformed(ActionEvent e) {
    	Object[] profileNames = Manager.getInstance().getProfileNames().toArray();
    	String selectedProfile = (String) JOptionPane.showInputDialog(this, 
    	        "Select a player.",
    	        "Profile Select",
    	        JOptionPane.QUESTION_MESSAGE, 
    	        null, 
    	        profileNames, 
    	        profileNames[0]);
    	
    	if (selectedProfile == null) { return; } // Cancel
    	Manager.getInstance().setCurrentProfile(selectedProfile);
    	updateProfile();
    }
    
    private void miCreateProfileActionPerformed(ActionEvent e) {
    	java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewProfile().setVisible(true);
            }
        });
    }
    
    private void miAddDiscActionPerformed(ActionEvent e) {
    	if (Manager.getInstance().getCurrentProfile() == null) {
    		JOptionPane.showMessageDialog(null, "No profile has been selected.");
    		return;
    	}
    	
    	Object[] discNames = Manager.getInstance().getDiscNames().toArray();
    	String selectedDisc = (String) JOptionPane.showInputDialog(this, 
    	        "Select the disc.",
    	        "Add Disc to Profile",
    	        JOptionPane.QUESTION_MESSAGE, 
    	        null, 
    	        discNames, 
    	        discNames[0]);
    	
    	if (selectedDisc == null) { return; }
    	Disc disc = Manager.getInstance().getDiscs().getDisc(selectedDisc);
    	Manager.getInstance().getCurrentProfile().addDiscToBag(disc);
    	updateProfile();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            	System.out.println(info);
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    /* BEGIN JFRAME VARS */
    private javax.swing.JButton btnPlayRound;
    private javax.swing.JButton btnRecommend;
    private javax.swing.JButton btnViewDiscs;
    private javax.swing.JButton btnViewGames;
    private javax.swing.JList<String> lDiscs;
    private javax.swing.JMenu mEdit;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenuBar mMenuBar;
    private javax.swing.JMenuItem miChangeProfile;
    private javax.swing.JMenuItem miCreateProfile;
    private javax.swing.JMenuItem miAddDisc;
    private javax.swing.JPanel pDiscDisplay;
    private javax.swing.JPanel pEncloser;
    private javax.swing.JPanel pProfilePic;
    private javax.swing.JPanel pProfileSummary;
    private javax.swing.JPanel pToolbar;
    private javax.swing.JScrollPane sDiscs;
    private javax.swing.JScrollPane sProfileSummary;
    private javax.swing.JTextArea tProfileSummary;
    private javax.swing.JToolBar tlToolBar;
    /* END JFRAME VARS */
}
