/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package testapp;

/**
 *
 * @author o607771
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pEncloser = new javax.swing.JPanel();
        pProfilePic = new javax.swing.JPanel();
        pDiscDisplay = new javax.swing.JPanel();
        sDiscs = new javax.swing.JScrollPane();
        lDiscs = new javax.swing.JList();
        pProfileSummary = new javax.swing.JPanel();
        sProfileSummary = new javax.swing.JScrollPane();
        tProfileSummary = new javax.swing.JTextArea();
        pToolbar = new javax.swing.JPanel();
        tlToolBar = new javax.swing.JToolBar();
        btnViewDiscs = new javax.swing.JButton();
        btnRecommend = new javax.swing.JButton();
        btnPlayRound = new javax.swing.JButton();
        btnViewGames = new javax.swing.JButton();
        mMenuBar = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        miChangeProfile = new javax.swing.JMenuItem();
        mEdit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pProfilePic.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout pProfilePicLayout = new javax.swing.GroupLayout(pProfilePic);
        pProfilePic.setLayout(pProfilePicLayout);
        pProfilePicLayout.setHorizontalGroup(
            pProfilePicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );
        pProfilePicLayout.setVerticalGroup(
            pProfilePicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pDiscDisplay.setBackground(new java.awt.Color(153, 255, 255));
        pDiscDisplay.setBorder(javax.swing.BorderFactory.createTitledBorder("Discs"));

        sDiscs.setViewportView(lDiscs);

        javax.swing.GroupLayout pDiscDisplayLayout = new javax.swing.GroupLayout(pDiscDisplay);
        pDiscDisplay.setLayout(pDiscDisplayLayout);
        pDiscDisplayLayout.setHorizontalGroup(
            pDiscDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDiscDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sDiscs, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );
        pDiscDisplayLayout.setVerticalGroup(
            pDiscDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDiscDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sDiscs, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );

        pProfileSummary.setBackground(new java.awt.Color(102, 204, 0));

        tProfileSummary.setColumns(20);
        tProfileSummary.setRows(5);
        sProfileSummary.setViewportView(tProfileSummary);

        javax.swing.GroupLayout pProfileSummaryLayout = new javax.swing.GroupLayout(pProfileSummary);
        pProfileSummary.setLayout(pProfileSummaryLayout);
        pProfileSummaryLayout.setHorizontalGroup(
            pProfileSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProfileSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sProfileSummary)
                .addContainerGap())
        );
        pProfileSummaryLayout.setVerticalGroup(
            pProfileSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProfileSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sProfileSummary)
                .addContainerGap())
        );

        pToolbar.setBackground(new java.awt.Color(204, 255, 255));

        tlToolBar.setBackground(new java.awt.Color(0, 153, 153));
        tlToolBar.setRollover(true);

        btnViewDiscs.setText("View Disc Catalogue");
        btnViewDiscs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnViewDiscsMousePressed(evt);
            }
        });
        tlToolBar.add(btnViewDiscs);

        btnRecommend.setText("Recommend a Disc!");
        btnRecommend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRecommendMousePressed(evt);
            }
        });
        tlToolBar.add(btnRecommend);

        btnPlayRound.setText("Play a Round!");
        btnPlayRound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPlayRoundMousePressed(evt);
            }
        });
        tlToolBar.add(btnPlayRound);

        btnViewGames.setText("View Past Games");
        btnViewGames.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnViewGamesMousePressed(evt);
            }
        });
        tlToolBar.add(btnViewGames);

        javax.swing.GroupLayout pToolbarLayout = new javax.swing.GroupLayout(pToolbar);
        pToolbar.setLayout(pToolbarLayout);
        pToolbarLayout.setHorizontalGroup(
            pToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tlToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pToolbarLayout.setVerticalGroup(
            pToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tlToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pEncloserLayout = new javax.swing.GroupLayout(pEncloser);
        pEncloser.setLayout(pEncloserLayout);
        pEncloserLayout.setHorizontalGroup(
            pEncloserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEncloserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEncloserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pEncloserLayout.createSequentialGroup()
                        .addComponent(pProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pDiscDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pProfileSummary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pEncloserLayout.setVerticalGroup(
            pEncloserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEncloserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEncloserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pProfilePic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pDiscDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pProfileSummary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mFile.setText("File");

        miChangeProfile.setText("Change Profile");
        miChangeProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miChangeProfileMouseClicked(evt);
            }
        });
        mFile.add(miChangeProfile);

        mMenuBar.add(mFile);

        mEdit.setText("Edit");
        mMenuBar.add(mEdit);

        setJMenuBar(mMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pEncloser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pEncloser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDiscsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewDiscsMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewDiscsMousePressed

    private void btnRecommendMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecommendMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecommendMousePressed

    private void btnPlayRoundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayRoundMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayRoundMousePressed

    private void btnViewGamesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewGamesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewGamesMousePressed

    private void miChangeProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miChangeProfileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_miChangeProfileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlayRound;
    private javax.swing.JButton btnRecommend;
    private javax.swing.JButton btnViewDiscs;
    private javax.swing.JButton btnViewGames;
    private javax.swing.JList lDiscs;
    private javax.swing.JMenu mEdit;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenuBar mMenuBar;
    private javax.swing.JMenuItem miChangeProfile;
    private javax.swing.JPanel pDiscDisplay;
    private javax.swing.JPanel pEncloser;
    private javax.swing.JPanel pProfilePic;
    private javax.swing.JPanel pProfileSummary;
    private javax.swing.JPanel pToolbar;
    private javax.swing.JScrollPane sDiscs;
    private javax.swing.JScrollPane sProfileSummary;
    private javax.swing.JTextArea tProfileSummary;
    private javax.swing.JToolBar tlToolBar;
    // End of variables declaration//GEN-END:variables
}
