/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package main.gui;

import java.util.ArrayList;
import java.util.Date;

import javax.swing.JOptionPane;

import manager.Manager;
import player.Profile;

/**
 *
 * @author o607771
 */
public class NewProfile extends javax.swing.JFrame {

    /**
     * Creates new form NewProfile
     */
    public NewProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pEncloser = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        txtDisplayName = new javax.swing.JTextField();
        txtStartDate = new javax.swing.JTextField();
        txtFavoriteCourse = new javax.swing.JTextField();
        txtFavoriteDisc = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        lblDisplayName = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        lblFavoriteCourse = new javax.swing.JLabel();
        lblFavoriteDisc = new javax.swing.JLabel();
        spnHolesInOne = new javax.swing.JSpinner();
        lblHolesInOne = new javax.swing.JLabel();
        cbHanded = new javax.swing.JComboBox();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblHanded = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        lblUsername.setText("Username:");

        lblDisplayName.setText("Display Name:");

        lblStartDate.setText("Start Date:");

        lblFavoriteCourse.setText("Favorite Course:");

        lblFavoriteDisc.setText("Favorite Disc:");

        lblHolesInOne.setText("Holes In One:");

        cbHanded.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Right Handed", "Left Handed", "Ambidextrous" }));

        btnCancel.setText("Cancel");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelMousePressed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSaveMousePressed(evt);
            }
        });

        lblHanded.setText("L/R Handed:");

        javax.swing.GroupLayout pEncloserLayout = new javax.swing.GroupLayout(pEncloser);
        pEncloser.setLayout(pEncloserLayout);
        pEncloserLayout.setHorizontalGroup(
            pEncloserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEncloserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEncloserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEncloserLayout.createSequentialGroup()
                        .addGroup(pEncloserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername)
                            .addComponent(lblDisplayName)
                            .addComponent(lblStartDate)
                            .addComponent(lblFavoriteCourse)
                            .addComponent(lblFavoriteDisc)
                            .addComponent(lblHolesInOne)
                            .addComponent(lblHanded))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addGroup(pEncloserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbHanded, 0, 171, Short.MAX_VALUE)
                            .addComponent(spnHolesInOne)
                            .addComponent(txtFavoriteDisc)
                            .addComponent(txtFavoriteCourse)
                            .addComponent(txtStartDate)
                            .addComponent(txtDisplayName)
                            .addComponent(txtUsername)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEncloserLayout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pEncloserLayout.setVerticalGroup(
            pEncloserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEncloserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEncloserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pEncloserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDisplayName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDisplayName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pEncloserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStartDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pEncloserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFavoriteCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFavoriteCourse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pEncloserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFavoriteDisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFavoriteDisc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pEncloserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnHolesInOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHolesInOne))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pEncloserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbHanded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHanded))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pEncloserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pEncloser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pEncloser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMousePressed
    	ArrayList<String> errors = getValidationErrors();
        if (!errors.isEmpty()){
        	String errorMsg = "Please fix the following errors:\n";
        	for (String error : errors) {
        		errorMsg += error + ", \n";
        	}
        	
        	JOptionPane.showMessageDialog(null, errorMsg);
        	return;
        }
        else { //Create the new profile
        	String username = txtUsername.getText();
        	boolean isRightHanded = ((String)cbHanded.getSelectedItem()).compareTo("Left Handed") != 0;

        	Manager.getInstance().getProfiles().put(username, 
        		new Profile(
        			username, 
        			txtDisplayName.getText(),
        			new Date(Integer.parseInt(txtStartDate.getText())),
        			isRightHanded,
        			txtFavoriteDisc.getText(),
        			txtFavoriteCourse.getText(),
        			0,
        			(int) spnHolesInOne.getValue(),
        			0, 0, 0, 0, 0,
        			0, 0, 0, 0, 0
        	));
        }
    }
    
    private ArrayList<String> getValidationErrors() {
    	ArrayList<String> errors = new ArrayList<String>();
    	
    	String username = txtUsername.getText();
    	if (username.isEmpty()) { errors.add("Username field is blank"); }
    	
    	return errors;
    }

    private void btnCancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cbHanded;
    private javax.swing.JLabel lblDisplayName;
    private javax.swing.JLabel lblFavoriteCourse;
    private javax.swing.JLabel lblFavoriteDisc;
    private javax.swing.JLabel lblHanded;
    private javax.swing.JLabel lblHolesInOne;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pEncloser;
    private javax.swing.JSpinner spnHolesInOne;
    private javax.swing.JTextField txtDisplayName;
    private javax.swing.JTextField txtFavoriteCourse;
    private javax.swing.JTextField txtFavoriteDisc;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
