/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package main.gui;

/**
 *
 * @author o607771
 */
public class PlayRound extends javax.swing.JFrame {

    /**
     * Creates new form DiscView
     */
    public PlayRound() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pScorecard = new javax.swing.JPanel();
        spScorecard = new javax.swing.JScrollPane();
        tblScorecard = new javax.swing.JTable();
        mbMenu = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        miLoadCourse = new javax.swing.JMenuItem();
        miFinishRound = new javax.swing.JMenuItem();
        miHoleMode = new javax.swing.JMenuItem();
        mEdit = new javax.swing.JMenu();
        miChangePlayers = new javax.swing.JMenuItem();
        miClear = new javax.swing.JMenuItem();
        miSelPlayer1 = new javax.swing.JMenuItem();
        miSelPlayer2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        tblScorecard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, null, null},
                {"2", null, null, null},
                {"3", null, null, null},
                {"4", null, null, null},
                {"5", null, null, null},
                {"6", null, null, null},
                {"7", null, null, null},
                {"8", null, null, null},
                {"9", null, null, null},
                {"10", null, null, null},
                {"11", null, null, null},
                {"12", null, null, null},
                {"13", null, null, null},
                {"14", null, null, null},
                {"15", null, null, null},
                {"16", null, null, null},
                {"17", null, null, null},
                {"18", null, null, null}
            },
            new String [] {
                "Hole #", "Par", "Player 1", "Player 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spScorecard.setViewportView(tblScorecard);

        javax.swing.GroupLayout pScorecardLayout = new javax.swing.GroupLayout(pScorecard);
        pScorecard.setLayout(pScorecardLayout);
        pScorecardLayout.setHorizontalGroup(
            pScorecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pScorecardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spScorecard)
                .addContainerGap())
        );
        pScorecardLayout.setVerticalGroup(
            pScorecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pScorecardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spScorecard, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
        );

        mFile.setText("File");

        miLoadCourse.setText("Load Course");
        miLoadCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                miLoadCourseMousePressed(evt);
            }
        });
        mFile.add(miLoadCourse);

        miFinishRound.setText("Finish Round");
        miFinishRound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                miFinishRoundMousePressed(evt);
            }
        });
        miFinishRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFinishRoundActionPerformed(evt);
            }
        });
        mFile.add(miFinishRound);

        miHoleMode.setText("Hole-by-hole Mode");
        miHoleMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                miHoleModeMousePressed(evt);
            }
        });
        mFile.add(miHoleMode);

        mbMenu.add(mFile);

        mEdit.setText("Edit");

        miChangePlayers.setText("Change # Players");
        miChangePlayers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                miChangePlayersMousePressed(evt);
            }
        });
        mEdit.add(miChangePlayers);

        miClear.setText("Clear Scores");
        miClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                miClearMousePressed(evt);
            }
        });
        mEdit.add(miClear);

        miSelPlayer1.setText("Select Player 1");
        miSelPlayer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                miSelPlayer1MousePressed(evt);
            }
        });
        mEdit.add(miSelPlayer1);

        miSelPlayer2.setText("Select Player 2");
        miSelPlayer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                miSelPlayer2MousePressed(evt);
            }
        });
        mEdit.add(miSelPlayer2);

        mbMenu.add(mEdit);

        setJMenuBar(mbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pScorecard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pScorecard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miFinishRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFinishRoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miFinishRoundActionPerformed

    private void miLoadCourseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miLoadCourseMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_miLoadCourseMousePressed

    private void miFinishRoundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miFinishRoundMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_miFinishRoundMousePressed

    private void miHoleModeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miHoleModeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_miHoleModeMousePressed

    private void miChangePlayersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miChangePlayersMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_miChangePlayersMousePressed

    private void miClearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miClearMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_miClearMousePressed

    private void miSelPlayer1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miSelPlayer1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_miSelPlayer1MousePressed

    private void miSelPlayer2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miSelPlayer2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_miSelPlayer2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayRound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayRound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayRound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayRound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayRound().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu mEdit;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenuBar mbMenu;
    private javax.swing.JMenuItem miChangePlayers;
    private javax.swing.JMenuItem miClear;
    private javax.swing.JMenuItem miFinishRound;
    private javax.swing.JMenuItem miHoleMode;
    private javax.swing.JMenuItem miLoadCourse;
    private javax.swing.JMenuItem miSelPlayer1;
    private javax.swing.JMenuItem miSelPlayer2;
    private javax.swing.JPanel pScorecard;
    private javax.swing.JScrollPane spScorecard;
    private javax.swing.JTable tblScorecard;
    // End of variables declaration//GEN-END:variables
}
